In [1]:
import pandas as pd

In [3]:
density_mergefee = pd.read_csv("D:\\Purdue\\research\\sensitivity_analysis\\density_mergefee_mile.csv")
density_mergefee

,City,County,Count,RetailerYear,RetailerCount_density,PopulationYear,Black.or.African.American,American.Indian.and.Alaska.Native,Asian,Native.Hawaiian.and.Other.Pacific.Islander,...,Bachelor_higher_25,smokefree,citylicense,pharmacyban,emerging_license,retailrestrict,flavored,EnactmentDate,AnnualFee,Application.Initial.Fee
0,Adelanto,San Bernardino,17,2012,0.303525,2010,0.208,0.008,0.030,0.015,...,0.07,1.0,0.0,0.0,NaN,NaN,NaN,12/2019,595.0,NaN
1,Adelanto,San Bernardino,17,2013,0.303525,2010,0.208,0.008,0.030,0.015,...,0.07,1.0,0.0,0.0,NaN,NaN,NaN,12/2019,595.0,NaN
2,Adelanto,San Bernardino,22,2014,0.392797,2010,0.208,0.008,0.030,0.015,...,0.07,0.0,0.0,1.0,NaN,NaN,NaN,12/2019,595.0,NaN
3,Adelanto,San Bernardino,19,2015,0.339234,2010,0.208,0.008,0.030,0.015,...,0.07,1.0,0.0,0.0,0.0,1.0,0.0,12/2019,595.0,NaN
4,Adelanto,San Bernardino,16,2016,0.285670,2010,0.208,0.008,0.030,0.015,...,0.07,1.0,0.0,0.0,0.0,1.0,0.0,12/2019,595.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4889,Yuba City,Sutter,78,2021,5.207047,2020,0.024,0.012,0.198,0.006,...,0.17,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
4890,Yuba City,Sutter,71,2022,4.739748,2020,0.024,0.012,0.198,0.006,...,0.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4891,Yucaipa,San Bernardino,48,2020,1.697967,2020,0.011,0.006,0.044,0.001,...,0.22,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
4892,Yucaipa,San Bernardino,49,2021,1.733341,2020,0.011,0.006,0.044,0.001,...,0.22,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
4893,Yucaipa,San Bernardino,52,2022,1.839464,2020,0.011,0.006,0.044,0.001,...,0.22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
unique_counts = density_mergefee['flavored'].value_counts()
unique_counts

0.0    2926
1.0     155
Name: flavored, dtype: int64

In [13]:
unique_counts = density_mergefee['RetailerYear'].value_counts()
unique_counts

2015    457
2014    454
2017    453
2013    448
2016    445
2018    442
2019    441
2012    439
2020    439
2021    438
2022    438
Name: RetailerYear, dtype: int64

In [5]:
density_mergefee[density_mergefee['flavored'] == 1.0]

,City,County,Count,RetailerYear,RetailerCount_density,PopulationYear,Black.or.African.American,American.Indian.and.Alaska.Native,Asian,Native.Hawaiian.and.Other.Pacific.Islander,...,Bachelor_higher_25,smokefree,citylicense,pharmacyban,emerging_license,retailrestrict,flavored,EnactmentDate,AnnualFee,Application.Initial.Fee
159,Berkeley,Alameda,103,2015,9.837443,2010,0.098,0.002,0.207,0.004,...,0.70,4.0,4.0,1.0,0.0,1.0,1.0,12/2002,427.0,NaN
561,El Cerrito,Contra Costa,17,2016,4.609919,2010,0.006,0.000,0.006,0.000,...,0.57,4.0,4.0,0.0,1.0,1.0,1.0,4/1999,439.0,485.0
795,Hayward,Alameda,163,2016,3.596400,2010,0.121,0.008,0.232,0.019,...,0.23,3.0,0.0,0.0,1.0,1.0,1.0,7/2014,400.0,NaN
1141,Manhattan Beach,Los Angeles,22,2016,5.587727,2010,0.003,0.002,0.067,0.001,...,0.73,4.0,3.0,0.0,0.0,1.0,1.0,12/2015,183.0,242.0
1599,Richmond,Contra Costa,81,2015,2.693912,2010,0.284,0.002,0.154,0.002,...,0.26,4.0,4.0,1.0,1.0,0.0,1.0,9/2019,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4831,Watsonville,Santa Cruz,63,2020,9.393732,2020,0.018,0.008,0.028,0.002,...,0.11,3.0,4.0,0.0,1.0,0.0,1.0,9/2010,255.0,NaN
4832,Watsonville,Santa Cruz,63,2021,9.393732,2020,0.018,0.008,0.028,0.002,...,0.11,3.0,4.0,1.0,1.0,0.0,1.0,9/2010,255.0,NaN
4844,West Sacramento,Yolo,50,2021,2.328863,2020,0.046,0.007,0.117,0.010,...,0.28,1.0,3.0,0.0,1.0,0.0,1.0,11/2009,427.0,NaN
4876,Woodland,Yolo,45,2020,2.938353,2020,0.017,0.012,0.079,0.002,...,0.25,2.0,4.0,0.0,1.0,0.0,1.0,6/2015,427.0,NaN
4877,Woodland,Yolo,43,2021,2.807760,2020,0.017,0.012,0.079,0.002,...,0.25,2.0,4.0,0.0,1.0,0.0,1.0,6/2015,427.0,NaN

In [8]:
# Filter rows based on conditions
filtered_df = density_mergefee[(density_mergefee['flavored'].isnull() | (density_mergefee['flavored'] == 0.0)) & (density_mergefee['RetailerYear'] < 2023)]

# Further filter rows based on conditions after 2023
filtered_df_after_2023 = density_mergefee[(density_mergefee['flavored'] == 1.0) & (density_mergefee['RetailerYear'] >= 2023)]

# Merge the filtered DataFrames on (city, county)
merged_df = pd.merge(filtered_df, filtered_df_after_2023, on=['City', 'County'])

# Select the (city, county) columns
result = merged_df[['City', 'County']]

# Drop duplicates if needed
result = result.drop_duplicates()
result

Empty DataFrame
Columns: [City, County]
Index: []

In [9]:
filtered_df

,City,County,Count,RetailerYear,RetailerCount_density,PopulationYear,Black.or.African.American,American.Indian.and.Alaska.Native,Asian,Native.Hawaiian.and.Other.Pacific.Islander,...,Bachelor_higher_25,smokefree,citylicense,pharmacyban,emerging_license,retailrestrict,flavored,EnactmentDate,AnnualFee,Application.Initial.Fee
0,Adelanto,San Bernardino,17,2012,0.303525,2010,0.208,0.008,0.030,0.015,...,0.07,1.0,0.0,0.0,NaN,NaN,NaN,12/2019,595.0,NaN
1,Adelanto,San Bernardino,17,2013,0.303525,2010,0.208,0.008,0.030,0.015,...,0.07,1.0,0.0,0.0,NaN,NaN,NaN,12/2019,595.0,NaN
2,Adelanto,San Bernardino,22,2014,0.392797,2010,0.208,0.008,0.030,0.015,...,0.07,0.0,0.0,1.0,NaN,NaN,NaN,12/2019,595.0,NaN
3,Adelanto,San Bernardino,19,2015,0.339234,2010,0.208,0.008,0.030,0.015,...,0.07,1.0,0.0,0.0,0.0,1.0,0.0,12/2019,595.0,NaN
4,Adelanto,San Bernardino,16,2016,0.285670,2010,0.208,0.008,0.030,0.015,...,0.07,1.0,0.0,0.0,0.0,1.0,0.0,12/2019,595.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4889,Yuba City,Sutter,78,2021,5.207047,2020,0.024,0.012,0.198,0.006,...,0.17,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
4890,Yuba City,Sutter,71,2022,4.739748,2020,0.024,0.012,0.198,0.006,...,0.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4891,Yucaipa,San Bernardino,48,2020,1.697967,2020,0.011,0.006,0.044,0.001,...,0.22,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
4892,Yucaipa,San Bernardino,49,2021,1.733341,2020,0.011,0.006,0.044,0.001,...,0.22,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
4893,Yucaipa,San Bernardino,52,2022,1.839464,2020,0.011,0.006,0.044,0.001,...,0.22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN